"""remove asset_type from stockprice

Revision ID: 3d6486bb32c8
Revises: 9d7510f5e4c7
Create Date: 2025-04-12 11:17:12.573559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6486bb32c8'
down_revision = '9d7510f5e4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_price', schema=None) as batch_op:
        batch_op.drop_column('asset_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_type', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
