"""Initial migration

Revision ID: 9d7510f5e4c7
Revises: 
Create Date: 2025-04-12 11:08:03.745989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d7510f5e4c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('asset_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('daily_change_pct', sa.Float(), nullable=True))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('asset_type')

    with op.batch_alter_table('stock_price', schema=None) as batch_op:
        batch_op.drop_column('daily_change_pct')
        batch_op.drop_column('asset_type')
        batch_op.drop_column('sector')

    # ### end Alembic commands ###
